### PR TITLE
If page has no ACL rules, use those of its parent.

### PR DESCRIPTION
**Pull request by beneva52**

### CODE REVIEW

**Comment by rhukster** [comment]
A few thoughts on this:

* I can see this being useful, although I think actually there are reasons why you **might not** want to check the parent level access. 
* This is a check that would happen on every page, so there is a performance implication there on every page that does not have an access header set. (could slow down every page load) 
* Why stop at the next up parent? What about multiple pages deep pages.

I think that this is a good idea, but needs a bit more flexibility:

* This should be a configuration option. Probably 2 levels of configuration:  
    1. login plugin configuration that enables/disables this functionality
    2. page level configuration to implicitly tell login plugin to check the parent page's access
* Configuration option to enable/disable climbing the page-structure-tree until an access level or root page if found (whichever happens first).

**Comment by beneva52** [comment]
You are right. I am new to Grav and don't know all the implications this check would have on performance.
I didn't know either that a page could have so many ancestors.
Concerning configuration, I agree with all of your propositons.

**Comment by flaviocopes** [comment]
@beneva52 I missed the PR updates! Merging it now, just tested. Good work!

**Comment by beneva52** [comment]
It's never too late!

**Pull request merged**
