### PR TITLE
Bugfix: Composer update + minor changes

### PR DESCRIPTION
**Pull request by Sommerregen**
This PR is for those who experience an [ERROR – Class ‘Grav\Plugin\Login\Controller’ not found](http://getgrav.org/forum#!/general:error-class-gravplugin). I did a `composer update` to avoid a most likely autoloading conflict.

Further I fixed a translation message and the "Remember Me" functionality. Unfortunately using `password_hash` is not the right thing here to use, since the hash changes between two sessions randomly and "Rememer Me" needs a fixed hash. That's why I'm using the hash function now.

### CODE REVIEW

**Comment by flaviocopes** [comment]
We're going to re-add the salt in Grav, but dynamically generated when you first setup the site, introduced by this commit https://github.com/getgrav/grav/commit/385233c508893176be6fbfc388661864b9cefdc7

Example of usage:
https://github.com/getgrav/grav/blob/34f83ebde2c7529bf2ab33e3cd17e8022aa7096f/system/src/Grav/Common/Utils.php#L453

So maybe you can use that (or fine with your code too, just informing we're re-adding a hash you can use to the config - just not one default that will never be changed, as it was before, but a dynamic one)

**Comment by flaviocopes** [comment]
I ditched `password_hash` too, not because of that problem (could use `password_verify` to verify match 2 different generated values), but because it was too expensive for the job

**Comment by Sommerregen** [comment]
Hi @flaviocopes oh, that's nice :smile:

Setting the salt for the "Remember Me" cookie here is not so important, since the cookie is already encrypted in a secure fashion. The salt used here is just to make sure, that we bind it to the browser of the user and the current system settings (cache key). Instead of using the system key, one could use the `config.security.salt` key in the future. But that's really optional and a design decision, which has no security impacts for the "Remember Me" cookie. If you like I can add that support, but as I told it is an optional feature.

Maybe we wait for @rhukster .

**Comment by rhukster** [comment]
Yah I think we should use the `config.security.salt` from now on.. it will be there and will be random per install.

**Comment by Sommerregen** [comment]
Ok, then leave this PR open for now. I'm waiting for the final implementation and add it then.

**Pull request merged**
